### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by MattSeen** [toabctl/jiracli#15]
Hey,

Nice utility. Just wondering if you encountered this error while testing:

```
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 175: character maps to <undefined>.
```
I'm guessing it's just some standard ascii/unicode issue?

Kind Regards,
- Matthew

**Comment by MattSeen** [comment]
Here is the full stacktrace.

```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\jiracli.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\jiracli\__init__.py", line 631, in main
    issue_search_result_print(jira_obj, args, args['issue_search'])
  File "C:\Python27\lib\site-packages\jiracli\__init__.py", line 264, in issue_search_result_print
    args['issue_oneline'])
  File "C:\Python27\lib\site-packages\jiracli\__init__.py", line 251, in issue_list_print
    for k, v in desc_fields.items()) + "\n")
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 175: character maps to <undefined>
```

**Comment by toabctl** [comment]
@MattSeen What version of `jiracli` are you using?

**Comment by MattSeen** [comment]
These are the version I'm using:

jira (0.50)
jiracli (0.4.3)

I'll grab a distro in a while and give it a go.

**Comment by MattSeen** [comment]
Hey @toabctl just tried out jiracli on a Linux on a VM. It's able to communicate with Jira and doesn't spit those errors all right. Any thoughts on how to mitigate this error on Windows?

**Comment by toabctl** [comment]
@MattSeen No. I don't have a windows machine here to test it. Sorry.

**Comment by MattSeen** [comment]
No problem. I'll play around with it when I have some time soon, might put in a pull request.

**Comment by toabctl** [comment]
@MattSeen ok. Thanks!

**Comment by toabctl** [comment]
@MattSeen any update here?
