### ISSUE TITLE
crash when ~/.jiracli.ini missing

### ISSUE THREAD

**Issue by cenekzach** [toabctl/jiracli#26]
jiracli is by default run in Python3:

```
$ cat `which jiracli`
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from jiracli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

But it uses `raw_input` function, which is not present in Python3 ([renamed to input](https://www.python.org/dev/peps/pep-3111/))

When `~/.jiracli.ini` is missing, a crash will occur:
```
$ jiracli -i Issue
Traceback (most recent call last):
  File "/usr/local/bin/jiracli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/jiracli/__init__.py", line 409, in main
    conf = config_get()
  File "/usr/local/lib/python3.4/dist-packages/jiracli/__init__.py", line 111, in config_get
    user, password, url = config_credentials_get()
  File "/usr/local/lib/python3.4/dist-packages/jiracli/__init__.py", line 73, in config_credentials_get
    user = raw_input("username:")
NameError: name 'raw_input' is not defined
```

**Comment by dsizzle** [comment]
This is still an issue, but the error message is different:

Traceback (most recent call last):
  File "/Users/xxxxx/venv-jira/bin/jiracli", line 7, in <module>
    from jiracli import main
ImportError: cannot import name main

If you run jiracli and exit when it asks for a username, you can easily reproduce this.
