### ISSUE TITLE
AttributeError: type object 'PropertyHolder' has no attribute 'reporter'

### ISSUE THREAD

**Issue by seebi** [toabctl/jiracli#50]
while searching my issues with

```
jiracli --issue-search "assignee=CurrentUser()"
```

I get the error

```
Traceback (most recent call last):
  File "/Users/seebi/.pyenv/versions/3.5.2/bin/jiracli", line 10, in <module>
    sys.exit(main())
  File "/Users/seebi/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/site-packages/jiracli/__init__.py", line 674, in main
    issue_search_result_print(jira_obj, args, args['issue_search'])
  File "/Users/seebi/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/site-packages/jiracli/__init__.py", line 277, in issue_search_result_print
    args['issue_oneline'])
  File "/Users/seebi/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/site-packages/jiracli/__init__.py", line 262, in issue_list_print
    show_trans=show_trans)
  File "/Users/seebi/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/site-packages/jiracli/__init__.py", line 191, in issue_format
    issue.fields.reporter.name)
AttributeError: type object 'PropertyHolder' has no attribute 'reporter'
```

always with the same issue

**Comment by toabctl** [comment]
@seebi I did a new release on pypi (0.4.9). Could you please verify that the problem is solved? TIA
